version: "3"

services:
  # --- SERVICES KAFKA ESSENTIELS ---
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,INTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092, INTERNAL://kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CREATE_TOPICS: "asteroid-data:3:1,planet-data:1:1,collision-alerts:1:1"
      KAFKA_LOG_RETENTION_BYTES: 1073741824
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    
  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - "8092:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=Asteroid-Tracker
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9093
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  # --- APPLICATION ASTEROIDES ---
  asteroid-app:
    build: ./app
    container_name: asteroid-app
    ports:
      - "8050:8050"
    depends_on:
      - kafka
    environment:
      - KAFKA_SERVERS=kafka:9092

volumes:
  asteroid_data: